/// Generated by mcp/scripts/gen-particle-types.cjs: change the generator, not this file.

/// bridge_differs(a, b)
/// @arg a
/// @arg b
/// @desc Whether two numbers differ by more than the 3 decimals the bridge speaks in.

function bridge_differs(a, b)
{
	return (abs(a - b) > 0.0001)
}

/// bridge_number_text_ok(text)
/// @arg text
/// @desc Whether the text is a plain number: digits, an optional leading minus and at most one decimal point.

function bridge_number_text_ok(text)
{
	var digits, dots, c;
	if (text = "")
		return false

	digits = 0
	dots = 0
	for (var i = 1; i <= string_length(text); i++)
	{
		c = string_char_at(text, i)
		if (c = "-" && i = 1)
			continue
		if (c = "." && dots = 0)
		{
			dots++
			continue
		}
		if (ord(c) >= ord("0") && ord(c) <= ord("9"))
		{
			digits++
			continue
		}
		return false
	}

	return (digits > 0)
}

/// bridge_range_error(value, name)
/// @arg value
/// @arg name
/// @desc Returns "" if the value is a number or a "min..max" text with min not above max, otherwise why not.

function bridge_range_error(val, name)
{
	var p, a, b, msg;
	msg = string(name) + " must be a number, or a text like min..max for a random value"
	if (is_real(val))
		return (is_bool(val) ? msg : "")
	if (!is_string(val))
		return msg

	p = string_pos("..", val)
	if (p = 0)
		return msg

	a = string_copy(val, 1, p - 1)
	b = string_copy(val, p + 2, string_length(val) - p - 1)
	if (!bridge_number_text_ok(a) || !bridge_number_text_ok(b))
		return msg
	if (real(a) > real(b))
		return string(name) + ": min must not be above max"

	return ""
}

/// bridge_range_min(text)
/// @arg text

function bridge_range_min(text)
{
	return real(string_copy(text, 1, string_pos("..", text) - 1))
}

/// bridge_range_max(text)
/// @arg text

function bridge_range_max(text)
{
	return real(string_copy(text, string_pos("..", text) + 2, string_length(text)))
}

/// bridge_range_text(min, max)
/// @arg min
/// @arg max

function bridge_range_text(mn, mx)
{
	return string_decimals(bridge_real(mn)) + ".." + string_decimals(bridge_real(mx))
}

/// bridge_color_range_error(value, name)
/// @arg value
/// @arg name
/// @desc Returns "" if the value is a colour "#RRGGBB" or two of them as "#RRGGBB..#RRGGBB", otherwise why not.

function bridge_color_range_error(val, name)
{
	var msg = string(name) + " must be a colour like #RRGGBB, or #RRGGBB..#RRGGBB for a random colour between two";
	if (!is_string(val))
		return msg
	if (string_length(val) = 7)
		return (bridge_is_hex_color(val) ? "" : msg)
	if (string_length(val) = 16 && string_copy(val, 8, 2) = ".." && bridge_is_hex_color(string_copy(val, 1, 7)) && bridge_is_hex_color(string_copy(val, 10, 7)))
		return ""

	return msg
}

/// bridge_ptype_names()
/// @desc Every particle type setting the bridge exposes, in the order they are applied.

function bridge_ptype_names()
{
	return array("name", "spawn_rate", "sprite_template", "sprite_animation_onend", "scale", "scale_add", "alpha", "alpha_add", "sprite_angle", "sprite_angle_add", "angle_speed", "angle_speed_add", "angle_speed_mul", "color_mix_time", "sprite_animation_speed", "angle", "spd", "spd_add", "spd_mul", "rot", "rot_spd", "rot_spd_add", "rot_spd_mul", "color", "color_mix", "spawn_region", "bounding_box", "bounce", "orbit", "color_mix_enabled", "sprite_template_still_frame", "sprite_template_random_frame", "sprite_template_reverse", "angle_extend", "spd_extend", "rot_extend", "rot_spd_extend", "bounce_factor", "sprite_frame_width", "sprite_frame_height", "sprite_frame_start", "sprite_frame_end")
}

/// bridge_ptype_kind(name)
/// @arg name
/// @desc "text", "spawnrate", "onend", "sprite", "range", "vector", "color", "bool" or "number" for a setting, "" if the name is not one.

function bridge_ptype_kind(name)
{
	switch (name)
	{
		case "name": return "text"
		case "spawn_rate": return "spawnrate"
		case "sprite_template": return "sprite"
		case "sprite_animation_onend": return "onend"
		case "scale": return "range"
		case "scale_add": return "range"
		case "alpha": return "range"
		case "alpha_add": return "range"
		case "sprite_angle": return "range"
		case "sprite_angle_add": return "range"
		case "angle_speed": return "range"
		case "angle_speed_add": return "range"
		case "angle_speed_mul": return "range"
		case "color_mix_time": return "range"
		case "sprite_animation_speed": return "range"
		case "angle": return "vector"
		case "spd": return "vector"
		case "spd_add": return "vector"
		case "spd_mul": return "vector"
		case "rot": return "vector"
		case "rot_spd": return "vector"
		case "rot_spd_add": return "vector"
		case "rot_spd_mul": return "vector"
		case "color": return "color"
		case "color_mix": return "color"
		case "spawn_region": return "bool"
		case "bounding_box": return "bool"
		case "bounce": return "bool"
		case "orbit": return "bool"
		case "color_mix_enabled": return "bool"
		case "sprite_template_still_frame": return "bool"
		case "sprite_template_random_frame": return "bool"
		case "sprite_template_reverse": return "bool"
		case "angle_extend": return "bool"
		case "spd_extend": return "bool"
		case "rot_extend": return "bool"
		case "rot_spd_extend": return "bool"
		case "bounce_factor": return "number"
		case "sprite_frame_width": return "number"
		case "sprite_frame_height": return "number"
		case "sprite_frame_start": return "number"
		case "sprite_frame_end": return "number"
	}

	return ""
}

/// bridge_ptype_map(ptype)
/// @arg ptype
/// @desc Returns a map of a particle type: its id and every setting. A random value is the text "min..max".

function bridge_ptype_map(p)
{
	var m, list;
	m = ds_map_create()
	m[?"id"] = p.save_id
	m[?"name"] = p.name
	m[?"spawn_rate"] = bridge_real(p.spawn_rate * 100)
	m[?"sprite_template"] = p.sprite_template
	if (p.sprite_animation_onend = 1)
		m[?"sprite_animation_onend"] = "loop"
	else if (p.sprite_animation_onend = 2)
		m[?"sprite_animation_onend"] = "reverse"
	else
		m[?"sprite_animation_onend"] = "stop"

	if (p.scale_israndom > 0)
		m[?"scale"] = bridge_range_text(p.scale_random_min, p.scale_random_max)
	else
		m[?"scale"] = bridge_real(p.scale)

	if (p.scale_add_israndom > 0)
		m[?"scale_add"] = bridge_range_text(p.scale_add_random_min, p.scale_add_random_max)
	else
		m[?"scale_add"] = bridge_real(p.scale_add)

	if (p.alpha_israndom > 0)
		m[?"alpha"] = bridge_range_text(p.alpha_random_min, p.alpha_random_max)
	else
		m[?"alpha"] = bridge_real(p.alpha)

	if (p.alpha_add_israndom > 0)
		m[?"alpha_add"] = bridge_range_text(p.alpha_add_random_min, p.alpha_add_random_max)
	else
		m[?"alpha_add"] = bridge_real(p.alpha_add)

	if (p.sprite_angle_israndom > 0)
		m[?"sprite_angle"] = bridge_range_text(p.sprite_angle_random_min, p.sprite_angle_random_max)
	else
		m[?"sprite_angle"] = bridge_real(p.sprite_angle)

	if (p.sprite_angle_add_israndom > 0)
		m[?"sprite_angle_add"] = bridge_range_text(p.sprite_angle_add_random_min, p.sprite_angle_add_random_max)
	else
		m[?"sprite_angle_add"] = bridge_real(p.sprite_angle_add)

	if (p.angle_speed_israndom > 0)
		m[?"angle_speed"] = bridge_range_text(p.angle_speed_random_min, p.angle_speed_random_max)
	else
		m[?"angle_speed"] = bridge_real(p.angle_speed)

	if (p.angle_speed_add_israndom > 0)
		m[?"angle_speed_add"] = bridge_range_text(p.angle_speed_add_random_min, p.angle_speed_add_random_max)
	else
		m[?"angle_speed_add"] = bridge_real(p.angle_speed_add)

	if (p.angle_speed_mul_israndom > 0)
		m[?"angle_speed_mul"] = bridge_range_text(p.angle_speed_mul_random_min, p.angle_speed_mul_random_max)
	else
		m[?"angle_speed_mul"] = bridge_real(p.angle_speed_mul)

	if (p.color_mix_time_israndom > 0)
		m[?"color_mix_time"] = bridge_range_text(p.color_mix_time_random_min, p.color_mix_time_random_max)
	else
		m[?"color_mix_time"] = bridge_real(p.color_mix_time)

	if (p.sprite_animation_speed_israndom > 0)
		m[?"sprite_animation_speed"] = bridge_range_text(p.sprite_animation_speed_random_min, p.sprite_animation_speed_random_max)
	else
		m[?"sprite_animation_speed"] = bridge_real(p.sprite_animation_speed)

	list = ds_list_create()
	for (var a = X; a <= Z; a++)
	{
		if (p.angle_israndom[a] > 0)
			ds_list_add(list, bridge_range_text(p.angle_random_min[a], p.angle_random_max[a]))
		else
			ds_list_add(list, bridge_real(p.angle[a]))
	}
	ds_map_add_list(m, "angle", list)

	list = ds_list_create()
	for (var a = X; a <= Z; a++)
	{
		if (p.spd_israndom[a] > 0)
			ds_list_add(list, bridge_range_text(p.spd_random_min[a], p.spd_random_max[a]))
		else
			ds_list_add(list, bridge_real(p.spd[a]))
	}
	ds_map_add_list(m, "spd", list)

	list = ds_list_create()
	for (var a = X; a <= Z; a++)
	{
		if (p.spd_add_israndom[a] > 0)
			ds_list_add(list, bridge_range_text(p.spd_add_random_min[a], p.spd_add_random_max[a]))
		else
			ds_list_add(list, bridge_real(p.spd_add[a]))
	}
	ds_map_add_list(m, "spd_add", list)

	list = ds_list_create()
	for (var a = X; a <= Z; a++)
	{
		if (p.spd_mul_israndom[a] > 0)
			ds_list_add(list, bridge_range_text(p.spd_mul_random_min[a], p.spd_mul_random_max[a]))
		else
			ds_list_add(list, bridge_real(p.spd_mul[a]))
	}
	ds_map_add_list(m, "spd_mul", list)

	list = ds_list_create()
	for (var a = X; a <= Z; a++)
	{
		if (p.rot_israndom[a] > 0)
			ds_list_add(list, bridge_range_text(p.rot_random_min[a], p.rot_random_max[a]))
		else
			ds_list_add(list, bridge_real(p.rot[a]))
	}
	ds_map_add_list(m, "rot", list)

	list = ds_list_create()
	for (var a = X; a <= Z; a++)
	{
		if (p.rot_spd_israndom[a] > 0)
			ds_list_add(list, bridge_range_text(p.rot_spd_random_min[a], p.rot_spd_random_max[a]))
		else
			ds_list_add(list, bridge_real(p.rot_spd[a]))
	}
	ds_map_add_list(m, "rot_spd", list)

	list = ds_list_create()
	for (var a = X; a <= Z; a++)
	{
		if (p.rot_spd_add_israndom[a] > 0)
			ds_list_add(list, bridge_range_text(p.rot_spd_add_random_min[a], p.rot_spd_add_random_max[a]))
		else
			ds_list_add(list, bridge_real(p.rot_spd_add[a]))
	}
	ds_map_add_list(m, "rot_spd_add", list)

	list = ds_list_create()
	for (var a = X; a <= Z; a++)
	{
		if (p.rot_spd_mul_israndom[a] > 0)
			ds_list_add(list, bridge_range_text(p.rot_spd_mul_random_min[a], p.rot_spd_mul_random_max[a]))
		else
			ds_list_add(list, bridge_real(p.rot_spd_mul[a]))
	}
	ds_map_add_list(m, "rot_spd_mul", list)

	if (p.color_israndom > 0)
		m[?"color"] = "#" + color_to_hex(p.color_random_start) + ".." + "#" + color_to_hex(p.color_random_end)
	else
		m[?"color"] = "#" + color_to_hex(p.color)

	if (p.color_mix_israndom > 0)
		m[?"color_mix"] = "#" + color_to_hex(p.color_mix_random_start) + ".." + "#" + color_to_hex(p.color_mix_random_end)
	else
		m[?"color_mix"] = "#" + color_to_hex(p.color_mix)

	m[?"spawn_region"] = (p.spawn_region > 0)
	m[?"bounding_box"] = (p.bounding_box > 0)
	m[?"bounce"] = (p.bounce > 0)
	m[?"orbit"] = (p.orbit > 0)
	m[?"color_mix_enabled"] = (p.color_mix_enabled > 0)
	m[?"sprite_template_still_frame"] = (p.sprite_template_still_frame > 0)
	m[?"sprite_template_random_frame"] = (p.sprite_template_random_frame > 0)
	m[?"sprite_template_reverse"] = (p.sprite_template_reverse > 0)
	m[?"angle_extend"] = (p.angle_extend > 0)
	m[?"spd_extend"] = (p.spd_extend > 0)
	m[?"rot_extend"] = (p.rot_extend > 0)
	m[?"rot_spd_extend"] = (p.rot_spd_extend > 0)
	m[?"bounce_factor"] = bridge_real(p.bounce_factor)
	m[?"sprite_frame_width"] = bridge_real(p.sprite_frame_width)
	m[?"sprite_frame_height"] = bridge_real(p.sprite_frame_height)
	m[?"sprite_frame_start"] = bridge_real(p.sprite_frame_start)
	m[?"sprite_frame_end"] = bridge_real(p.sprite_frame_end)

	return m
}

/// bridge_ptype_error(name, value)
/// @arg name
/// @arg value
/// @arg settings
/// @desc Returns "" if the particle type setting can be applied with this value, otherwise why not.
/// settings is the decoded request object that holds the value, to tell a list from a number.
/// A message starting with "Unknown sprite" means the sprite template was not found.

function bridge_ptype_error(name, val, settings)
{
	var err;
	if (bridge_ptype_kind(name) != "vector" && bridge_map_item_type(settings, name) != 0)
		return string(name) + " has the wrong kind of value"

	switch (bridge_ptype_kind(name))
	{
		case "text":
			if (!is_string(val) || val = "" || string_length(val) > 100)
				return "name must be a text of 1 to 100 characters"
			return ""

		case "spawnrate":
			if (!is_real(val) || is_bool(val) || val < 0 || val > 100)
				return "spawn_rate must be a percentage from 0 to 100"
			return ""

		case "sprite":
		{
			if (!is_string(val))
				return "sprite_template must be a sprite name, see list_names kind particle_sprites"
			for (var i = 0; i < ds_list_size(particle_template_list); i++)
				if (particle_template_list[|i].name = val)
					return ""
			return "Unknown sprite " + string(val) + ", see list_names kind particle_sprites"
		}

		case "onend":
			if (!is_string(val) || (val != "stop" && val != "loop" && val != "reverse"))
				return "sprite_animation_onend must be stop, loop or reverse"
			return ""

		case "range":
			return bridge_range_error(val, name)

		case "vector":
		{
			if (bridge_map_item_type(settings, name) != ds_type_list || ds_list_size(val) != 3)
				return string(name) + " must be a list of three values [x, y, z], each a number, a min..max text or null"
			for (var a = 0; a < 3; a++)
			{
				if (bridge_list_item_type(val, a) != 0)
					return string(name) + " must be a list of three values [x, y, z], each a number, a min..max text or null"
				if (is_real(val[|a]) && !is_bool(val[|a]) && val[|a] = null)
					continue
				err = bridge_range_error(val[|a], name)
				if (err != "")
					return err
			}
			return ""
		}

		case "color":
			return bridge_color_range_error(val, name)

		case "bool":
			if (!is_bool(val))
				return string(name) + " must be true or false"
			return ""

		case "number":
			return bridge_number_error(name, val)
	}

	return "Unknown particle type setting " + string(name)
}

/// bridge_ptype_apply(ptype, name, value)
/// @arg ptype
/// @arg name
/// @arg value
/// @desc Applies one checked setting through the app's actions. The particle spawner template must be temp_edit.
/// The changes are undo steps of their own: a count of the steps is up to the caller.

function bridge_ptype_apply(p, name, val)
{
	var num, mn, mx, item, from, to;
	ptype_edit = p

	switch (name)
	{
		case "name":
			if (p.name != val)
				action_lib_pc_type_name(string(val))
			break

		case "spawn_rate":
			num = bridge_real(val)
			if (bridge_differs(p.spawn_rate * 100, num))
				action_lib_pc_type_spawn_rate(num, 0)
			break

		case "sprite_template":
			if (p.sprite_template != val)
				action_lib_pc_type_sprite_template(string(val))
			break

		case "sprite_animation_onend":
		{
			num = 0
			if (val = "loop")
				num = 1
			else if (val = "reverse")
				num = 2
			if (p.sprite_animation_onend != num)
				action_lib_pc_type_sprite_animation_onend(num)
			break
		}

		case "scale":
		{
			if (is_string(val))
			{
				mn = bridge_range_min(val)
				mx = bridge_range_max(val)
				if (!(p.scale_israndom > 0))
					action_lib_pc_type_scale_israndom(true)
				if (bridge_differs(p.scale_random_min, mn))
					action_lib_pc_type_scale_random_min(mn * 1, 0)
				if (bridge_differs(p.scale_random_max, mx))
					action_lib_pc_type_scale_random_max(mx * 1, 0)
			}
			else
			{
				num = bridge_real(val)
				if (p.scale_israndom > 0)
					action_lib_pc_type_scale_israndom(false)
				if (bridge_differs(p.scale, num))
					action_lib_pc_type_scale(num * 1, 0)
			}
			break
		}

		case "scale_add":
		{
			if (is_string(val))
			{
				mn = bridge_range_min(val)
				mx = bridge_range_max(val)
				if (!(p.scale_add_israndom > 0))
					action_lib_pc_type_scale_add_israndom(true)
				if (bridge_differs(p.scale_add_random_min, mn))
					action_lib_pc_type_scale_add_random_min(mn * 1, 0)
				if (bridge_differs(p.scale_add_random_max, mx))
					action_lib_pc_type_scale_add_random_max(mx * 1, 0)
			}
			else
			{
				num = bridge_real(val)
				if (p.scale_add_israndom > 0)
					action_lib_pc_type_scale_add_israndom(false)
				if (bridge_differs(p.scale_add, num))
					action_lib_pc_type_scale_add(num * 1, 0)
			}
			break
		}

		case "alpha":
		{
			if (is_string(val))
			{
				mn = bridge_range_min(val)
				mx = bridge_range_max(val)
				if (!(p.alpha_israndom > 0))
					action_lib_pc_type_alpha_israndom(true)
				if (bridge_differs(p.alpha_random_min, mn))
					action_lib_pc_type_alpha_random_min(mn * 100, 0)
				if (bridge_differs(p.alpha_random_max, mx))
					action_lib_pc_type_alpha_random_max(mx * 100, 0)
			}
			else
			{
				num = bridge_real(val)
				if (p.alpha_israndom > 0)
					action_lib_pc_type_alpha_israndom(false)
				if (bridge_differs(p.alpha, num))
					action_lib_pc_type_alpha(num * 100, 0)
			}
			break
		}

		case "alpha_add":
		{
			if (is_string(val))
			{
				mn = bridge_range_min(val)
				mx = bridge_range_max(val)
				if (!(p.alpha_add_israndom > 0))
					action_lib_pc_type_alpha_add_israndom(true)
				if (bridge_differs(p.alpha_add_random_min, mn))
					action_lib_pc_type_alpha_add_random_min(mn * 100, 0)
				if (bridge_differs(p.alpha_add_random_max, mx))
					action_lib_pc_type_alpha_add_random_max(mx * 100, 0)
			}
			else
			{
				num = bridge_real(val)
				if (p.alpha_add_israndom > 0)
					action_lib_pc_type_alpha_add_israndom(false)
				if (bridge_differs(p.alpha_add, num))
					action_lib_pc_type_alpha_add(num * 100, 0)
			}
			break
		}

		case "sprite_angle":
		{
			if (is_string(val))
			{
				mn = bridge_range_min(val)
				mx = bridge_range_max(val)
				if (!(p.sprite_angle_israndom > 0))
					action_lib_pc_type_sprite_angle_israndom(true)
				if (bridge_differs(p.sprite_angle_random_min, mn))
					action_lib_pc_type_sprite_angle_random_min(mn * 1, 0)
				if (bridge_differs(p.sprite_angle_random_max, mx))
					action_lib_pc_type_sprite_angle_random_max(mx * 1, 0)
			}
			else
			{
				num = bridge_real(val)
				if (p.sprite_angle_israndom > 0)
					action_lib_pc_type_sprite_angle_israndom(false)
				if (bridge_differs(p.sprite_angle, num))
					action_lib_pc_type_sprite_angle(num * 1, 0)
			}
			break
		}

		case "sprite_angle_add":
		{
			if (is_string(val))
			{
				mn = bridge_range_min(val)
				mx = bridge_range_max(val)
				if (!(p.sprite_angle_add_israndom > 0))
					action_lib_pc_type_sprite_angle_add_israndom(true)
				if (bridge_differs(p.sprite_angle_add_random_min, mn))
					action_lib_pc_type_sprite_angle_add_random_min(mn * 1, 0)
				if (bridge_differs(p.sprite_angle_add_random_max, mx))
					action_lib_pc_type_sprite_angle_add_random_max(mx * 1, 0)
			}
			else
			{
				num = bridge_real(val)
				if (p.sprite_angle_add_israndom > 0)
					action_lib_pc_type_sprite_angle_add_israndom(false)
				if (bridge_differs(p.sprite_angle_add, num))
					action_lib_pc_type_sprite_angle_add(num * 1, 0)
			}
			break
		}

		case "angle_speed":
		{
			if (is_string(val))
			{
				mn = bridge_range_min(val)
				mx = bridge_range_max(val)
				if (!(p.angle_speed_israndom > 0))
					action_lib_pc_type_angle_speed_israndom(true)
				if (bridge_differs(p.angle_speed_random_min, mn))
					action_lib_pc_type_angle_speed_random_min(mn * 1, 0)
				if (bridge_differs(p.angle_speed_random_max, mx))
					action_lib_pc_type_angle_speed_random_max(mx * 1, 0)
			}
			else
			{
				num = bridge_real(val)
				if (p.angle_speed_israndom > 0)
					action_lib_pc_type_angle_speed_israndom(false)
				if (bridge_differs(p.angle_speed, num))
					action_lib_pc_type_angle_speed(num * 1, 0)
			}
			break
		}

		case "angle_speed_add":
		{
			if (is_string(val))
			{
				mn = bridge_range_min(val)
				mx = bridge_range_max(val)
				if (!(p.angle_speed_add_israndom > 0))
					action_lib_pc_type_angle_speed_add_israndom(true)
				if (bridge_differs(p.angle_speed_add_random_min, mn))
					action_lib_pc_type_angle_speed_add_random_min(mn * 1, 0)
				if (bridge_differs(p.angle_speed_add_random_max, mx))
					action_lib_pc_type_angle_speed_add_random_max(mx * 1, 0)
			}
			else
			{
				num = bridge_real(val)
				if (p.angle_speed_add_israndom > 0)
					action_lib_pc_type_angle_speed_add_israndom(false)
				if (bridge_differs(p.angle_speed_add, num))
					action_lib_pc_type_angle_speed_add(num * 1, 0)
			}
			break
		}

		case "angle_speed_mul":
		{
			if (is_string(val))
			{
				mn = bridge_range_min(val)
				mx = bridge_range_max(val)
				if (!(p.angle_speed_mul_israndom > 0))
					action_lib_pc_type_angle_speed_mul_israndom(true)
				if (bridge_differs(p.angle_speed_mul_random_min, mn))
					action_lib_pc_type_angle_speed_mul_random_min(mn * 1, 0)
				if (bridge_differs(p.angle_speed_mul_random_max, mx))
					action_lib_pc_type_angle_speed_mul_random_max(mx * 1, 0)
			}
			else
			{
				num = bridge_real(val)
				if (p.angle_speed_mul_israndom > 0)
					action_lib_pc_type_angle_speed_mul_israndom(false)
				if (bridge_differs(p.angle_speed_mul, num))
					action_lib_pc_type_angle_speed_mul(num * 1, 0)
			}
			break
		}

		case "color_mix_time":
		{
			if (is_string(val))
			{
				mn = bridge_range_min(val)
				mx = bridge_range_max(val)
				if (!(p.color_mix_time_israndom > 0))
					action_lib_pc_type_color_mix_time_israndom(true)
				if (bridge_differs(p.color_mix_time_random_min, mn))
					action_lib_pc_type_color_mix_time_random_min(mn * 1, 0)
				if (bridge_differs(p.color_mix_time_random_max, mx))
					action_lib_pc_type_color_mix_time_random_max(mx * 1, 0)
			}
			else
			{
				num = bridge_real(val)
				if (p.color_mix_time_israndom > 0)
					action_lib_pc_type_color_mix_time_israndom(false)
				if (bridge_differs(p.color_mix_time, num))
					action_lib_pc_type_color_mix_time(num * 1, 0)
			}
			break
		}

		case "sprite_animation_speed":
		{
			if (is_string(val))
			{
				mn = bridge_range_min(val)
				mx = bridge_range_max(val)
				if (!(p.sprite_animation_speed_israndom > 0))
					action_lib_pc_type_sprite_animation_speed_israndom(true)
				if (bridge_differs(p.sprite_animation_speed_random_min, mn))
					action_lib_pc_type_sprite_animation_speed_random_min(mn * 1, 0)
				if (bridge_differs(p.sprite_animation_speed_random_max, mx))
					action_lib_pc_type_sprite_animation_speed_random_max(mx * 1, 0)
			}
			else
			{
				num = bridge_real(val)
				if (p.sprite_animation_speed_israndom > 0)
					action_lib_pc_type_sprite_animation_speed_israndom(false)
				if (bridge_differs(p.sprite_animation_speed, num))
					action_lib_pc_type_sprite_animation_speed(num * 1, 0)
			}
			break
		}

		case "angle":
		{
			for (var a = X; a <= Z; a++)
			{
				item = val[|a]
				if (is_real(item) && !is_bool(item) && item = null)
					continue
				axis_edit = a
				if (is_string(item))
				{
					mn = bridge_range_min(item)
					mx = bridge_range_max(item)
					if (!(p.angle_israndom[a] > 0))
						action_lib_pc_type_angle_israndom(true)
					if (bridge_differs(p.angle_random_min[a], mn))
						action_lib_pc_type_angle_random_min(mn, 0)
					if (bridge_differs(p.angle_random_max[a], mx))
						action_lib_pc_type_angle_random_max(mx, 0)
				}
				else
				{
					num = bridge_real(item)
					if (p.angle_israndom[a] > 0)
						action_lib_pc_type_angle_israndom(false)
					if (bridge_differs(p.angle[a], num))
						action_lib_pc_type_angle(num, 0)
				}
			}
			break
		}

		case "spd":
		{
			for (var a = X; a <= Z; a++)
			{
				item = val[|a]
				if (is_real(item) && !is_bool(item) && item = null)
					continue
				axis_edit = a
				if (is_string(item))
				{
					mn = bridge_range_min(item)
					mx = bridge_range_max(item)
					if (!(p.spd_israndom[a] > 0))
						action_lib_pc_type_spd_israndom(true)
					if (bridge_differs(p.spd_random_min[a], mn))
						action_lib_pc_type_spd_random_min(mn, 0)
					if (bridge_differs(p.spd_random_max[a], mx))
						action_lib_pc_type_spd_random_max(mx, 0)
				}
				else
				{
					num = bridge_real(item)
					if (p.spd_israndom[a] > 0)
						action_lib_pc_type_spd_israndom(false)
					if (bridge_differs(p.spd[a], num))
						action_lib_pc_type_spd(num, 0)
				}
			}
			break
		}

		case "spd_add":
		{
			for (var a = X; a <= Z; a++)
			{
				item = val[|a]
				if (is_real(item) && !is_bool(item) && item = null)
					continue
				axis_edit = a
				if (is_string(item))
				{
					mn = bridge_range_min(item)
					mx = bridge_range_max(item)
					if (!(p.spd_add_israndom[a] > 0))
						action_lib_pc_type_spd_add_israndom(true)
					if (bridge_differs(p.spd_add_random_min[a], mn))
						action_lib_pc_type_spd_add_random_min(mn, 0)
					if (bridge_differs(p.spd_add_random_max[a], mx))
						action_lib_pc_type_spd_add_random_max(mx, 0)
				}
				else
				{
					num = bridge_real(item)
					if (p.spd_add_israndom[a] > 0)
						action_lib_pc_type_spd_add_israndom(false)
					if (bridge_differs(p.spd_add[a], num))
						action_lib_pc_type_spd_add(num, 0)
				}
			}
			break
		}

		case "spd_mul":
		{
			for (var a = X; a <= Z; a++)
			{
				item = val[|a]
				if (is_real(item) && !is_bool(item) && item = null)
					continue
				axis_edit = a
				if (is_string(item))
				{
					mn = bridge_range_min(item)
					mx = bridge_range_max(item)
					if (!(p.spd_mul_israndom[a] > 0))
						action_lib_pc_type_spd_mul_israndom(true)
					if (bridge_differs(p.spd_mul_random_min[a], mn))
						action_lib_pc_type_spd_mul_random_min(mn, 0)
					if (bridge_differs(p.spd_mul_random_max[a], mx))
						action_lib_pc_type_spd_mul_random_max(mx, 0)
				}
				else
				{
					num = bridge_real(item)
					if (p.spd_mul_israndom[a] > 0)
						action_lib_pc_type_spd_mul_israndom(false)
					if (bridge_differs(p.spd_mul[a], num))
						action_lib_pc_type_spd_mul(num, 0)
				}
			}
			break
		}

		case "rot":
		{
			for (var a = X; a <= Z; a++)
			{
				item = val[|a]
				if (is_real(item) && !is_bool(item) && item = null)
					continue
				axis_edit = a
				if (is_string(item))
				{
					mn = bridge_range_min(item)
					mx = bridge_range_max(item)
					if (!(p.rot_israndom[a] > 0))
						action_lib_pc_type_rot_israndom(true)
					if (bridge_differs(p.rot_random_min[a], mn))
						action_lib_pc_type_rot_random_min(mn, 0)
					if (bridge_differs(p.rot_random_max[a], mx))
						action_lib_pc_type_rot_random_max(mx, 0)
				}
				else
				{
					num = bridge_real(item)
					if (p.rot_israndom[a] > 0)
						action_lib_pc_type_rot_israndom(false)
					if (bridge_differs(p.rot[a], num))
						action_lib_pc_type_rot(num, 0)
				}
			}
			break
		}

		case "rot_spd":
		{
			for (var a = X; a <= Z; a++)
			{
				item = val[|a]
				if (is_real(item) && !is_bool(item) && item = null)
					continue
				axis_edit = a
				if (is_string(item))
				{
					mn = bridge_range_min(item)
					mx = bridge_range_max(item)
					if (!(p.rot_spd_israndom[a] > 0))
						action_lib_pc_type_rot_spd_israndom(true)
					if (bridge_differs(p.rot_spd_random_min[a], mn))
						action_lib_pc_type_rot_spd_random_min(mn, 0)
					if (bridge_differs(p.rot_spd_random_max[a], mx))
						action_lib_pc_type_rot_spd_random_max(mx, 0)
				}
				else
				{
					num = bridge_real(item)
					if (p.rot_spd_israndom[a] > 0)
						action_lib_pc_type_rot_spd_israndom(false)
					if (bridge_differs(p.rot_spd[a], num))
						action_lib_pc_type_rot_spd(num, 0)
				}
			}
			break
		}

		case "rot_spd_add":
		{
			for (var a = X; a <= Z; a++)
			{
				item = val[|a]
				if (is_real(item) && !is_bool(item) && item = null)
					continue
				axis_edit = a
				if (is_string(item))
				{
					mn = bridge_range_min(item)
					mx = bridge_range_max(item)
					if (!(p.rot_spd_add_israndom[a] > 0))
						action_lib_pc_type_rot_spd_add_israndom(true)
					if (bridge_differs(p.rot_spd_add_random_min[a], mn))
						action_lib_pc_type_rot_spd_add_random_min(mn, 0)
					if (bridge_differs(p.rot_spd_add_random_max[a], mx))
						action_lib_pc_type_rot_spd_add_random_max(mx, 0)
				}
				else
				{
					num = bridge_real(item)
					if (p.rot_spd_add_israndom[a] > 0)
						action_lib_pc_type_rot_spd_add_israndom(false)
					if (bridge_differs(p.rot_spd_add[a], num))
						action_lib_pc_type_rot_spd_add(num, 0)
				}
			}
			break
		}

		case "rot_spd_mul":
		{
			for (var a = X; a <= Z; a++)
			{
				item = val[|a]
				if (is_real(item) && !is_bool(item) && item = null)
					continue
				axis_edit = a
				if (is_string(item))
				{
					mn = bridge_range_min(item)
					mx = bridge_range_max(item)
					if (!(p.rot_spd_mul_israndom[a] > 0))
						action_lib_pc_type_rot_spd_mul_israndom(true)
					if (bridge_differs(p.rot_spd_mul_random_min[a], mn))
						action_lib_pc_type_rot_spd_mul_random_min(mn, 0)
					if (bridge_differs(p.rot_spd_mul_random_max[a], mx))
						action_lib_pc_type_rot_spd_mul_random_max(mx, 0)
				}
				else
				{
					num = bridge_real(item)
					if (p.rot_spd_mul_israndom[a] > 0)
						action_lib_pc_type_rot_spd_mul_israndom(false)
					if (bridge_differs(p.rot_spd_mul[a], num))
						action_lib_pc_type_rot_spd_mul(num, 0)
				}
			}
			break
		}

		case "color":
		{
			if (string_length(val) > 7)
			{
				from = hex_to_color(string_copy(val, 1, 7))
				to = hex_to_color(string_copy(val, 10, 7))
				if (!(p.color_israndom > 0))
					action_lib_pc_type_color_israndom(true)
				if (p.color_random_start != from)
					action_lib_pc_type_color_random_start(from)
				if (p.color_random_end != to)
					action_lib_pc_type_color_random_end(to)
			}
			else
			{
				from = hex_to_color(string(val))
				if (p.color_israndom > 0)
					action_lib_pc_type_color_israndom(false)
				if (p.color != from)
					action_lib_pc_type_color(from)
			}
			break
		}

		case "color_mix":
		{
			if (string_length(val) > 7)
			{
				from = hex_to_color(string_copy(val, 1, 7))
				to = hex_to_color(string_copy(val, 10, 7))
				if (!(p.color_mix_israndom > 0))
					action_lib_pc_type_color_mix_israndom(true)
				if (p.color_mix_random_start != from)
					action_lib_pc_type_color_mix_random_start(from)
				if (p.color_mix_random_end != to)
					action_lib_pc_type_color_mix_random_end(to)
			}
			else
			{
				from = hex_to_color(string(val))
				if (p.color_mix_israndom > 0)
					action_lib_pc_type_color_mix_israndom(false)
				if (p.color_mix != from)
					action_lib_pc_type_color_mix(from)
			}
			break
		}

		case "spawn_region":
			if ((p.spawn_region > 0) != (val > 0))
				action_lib_pc_type_spawn_region((val > 0))
			break

		case "bounding_box":
			if ((p.bounding_box > 0) != (val > 0))
				action_lib_pc_type_bounding_box((val > 0))
			break

		case "bounce":
			if ((p.bounce > 0) != (val > 0))
				action_lib_pc_type_bounce((val > 0))
			break

		case "orbit":
			if ((p.orbit > 0) != (val > 0))
				action_lib_pc_type_orbit((val > 0))
			break

		case "color_mix_enabled":
			if ((p.color_mix_enabled > 0) != (val > 0))
				action_lib_pc_type_color_mix_enabled((val > 0))
			break

		case "sprite_template_still_frame":
			if ((p.sprite_template_still_frame > 0) != (val > 0))
				action_lib_pc_type_sprite_template_still_frame((val > 0))
			break

		case "sprite_template_random_frame":
			if ((p.sprite_template_random_frame > 0) != (val > 0))
				action_lib_pc_type_sprite_template_random_frame((val > 0))
			break

		case "sprite_template_reverse":
			if ((p.sprite_template_reverse > 0) != (val > 0))
				action_lib_pc_type_sprite_template_reverse((val > 0))
			break

		case "angle_extend":
			if ((p.angle_extend > 0) != (val > 0))
				action_lib_pc_type_angle_extend((val > 0))
			break

		case "spd_extend":
			if ((p.spd_extend > 0) != (val > 0))
				action_lib_pc_type_spd_extend((val > 0))
			break

		case "rot_extend":
			if ((p.rot_extend > 0) != (val > 0))
				action_lib_pc_type_rot_extend((val > 0))
			break

		case "rot_spd_extend":
			if ((p.rot_spd_extend > 0) != (val > 0))
				action_lib_pc_type_rot_spd_extend((val > 0))
			break

		case "bounce_factor":
			num = bridge_real(val)
			if (bridge_differs(p.bounce_factor, num))
				action_lib_pc_type_bounce_factor(num, 0)
			break

		case "sprite_frame_width":
			num = round(val)
			if (bridge_differs(p.sprite_frame_width, num))
				action_lib_pc_type_sprite_frame_width(num, 0)
			break

		case "sprite_frame_height":
			num = round(val)
			if (bridge_differs(p.sprite_frame_height, num))
				action_lib_pc_type_sprite_frame_height(num, 0)
			break

		case "sprite_frame_start":
			num = round(val)
			if (bridge_differs(p.sprite_frame_start, num))
				action_lib_pc_type_sprite_frame_start(num, 0)
			break

		case "sprite_frame_end":
			num = round(val)
			if (bridge_differs(p.sprite_frame_end, num))
				action_lib_pc_type_sprite_frame_end(num, 0)
			break

	}
}

/// bridge_number_error(name, value)
/// @arg name
/// @arg value
/// @desc Checks the plain number settings of a particle type.

function bridge_number_error(name, val)
{
	if (!is_real(val) || is_bool(val))
		return string(name) + " must be a number"

	if (name = "bounce_factor")
	{
		if (val < 0 || val > 10)
			return "bounce_factor must be a number from 0 to 10"
		return ""
	}

	if (name = "sprite_frame_width")
	{
		if (val < 1 || val > 4096 || val != round(val))
			return "sprite_frame_width must be a whole number from 1 to 4096"
		return ""
	}

	if (name = "sprite_frame_height")
	{
		if (val < 1 || val > 4096 || val != round(val))
			return "sprite_frame_height must be a whole number from 1 to 4096"
		return ""
	}

	if (name = "sprite_frame_start")
	{
		if (val < 0 || val > 4096 || val != round(val))
			return "sprite_frame_start must be a whole number from 0 to 4096"
		return ""
	}

	if (name = "sprite_frame_end")
	{
		if (val < 0 || val > 4096 || val != round(val))
			return "sprite_frame_end must be a whole number from 0 to 4096"
		return ""
	}

	return ""
}

